(ns ol.trixnity.key
  "Encryption-key state, backup state, and trust-level queries.

  ## Upstream Mapping

  This namespace maps to Trixnity's `KeyService` and `KeyBackupService`.

  The public wrappers here cover:

  - current and flow-based backup bootstrap state
  - cross-signing bootstrap
  - current and flow-based backup-version observation
  - trust-level queries for users, devices, and timeline events
  - device-key and cross-signing-key lookup

  Use [[ol.trixnity.verification]] for active verification workflows and
  [[ol.trixnity.room]] when you need room timeline events to pair with
  trust-level checks."
  (:require
   [clojure.string :as str]
   [missionary.core :as m]
   [ol.trixnity.internal :as internal]
   [ol.trixnity.internal.bridge :as bridge]
   [ol.trixnity.schemas :as mx]))

(set! *warn-on-reflection* true)

(defn current-bootstrap-running
  "Returns whether cross-signing bootstrap is currently running."
  [client]
  (boolean (bridge/current-bootstrap-running client)))

(defn bootstrap-running
  "Returns a Missionary flow of cross-signing bootstrap state."
  [client]
  (->> (internal/observe-flow client (bridge/bootstrap-running-flow client))
       (m/relieve {})))

(defn bootstrap-cross-signing!
  "Bootstraps cross-signing for the current Matrix account.

  Returns a Missionary task. The task resolves to a normalized map with:

  - `::mx/kind` — `\"success\"`, `\"uia-required\"`, or `\"uia-error\"`
  - `::mx/recovery-key` — the recovery key generated by Trixnity
  - `::mx/uia` — a UIA snapshot with completed stages, flows, session, and error details

  By default this calls Trixnity's `KeyService.bootstrapCrossSigning()`. If
  `opts` includes `::mx/password`, the bridge attempts to complete a password
  UIA step before returning. `::mx/user-id` can override the password UIA user
  identifier; otherwise the current client's Matrix user id is used.

  `\"uia-required\"` and `\"uia-error\"` results do not expose Trixnity UIA
  objects. Inspect `::mx/uia` to decide which public UIA flow or error remains.

  Persist or display `::mx/recovery-key` securely; it is the user's recovery
  key material for the new bootstrap.

  Be aware that upstream cross-signing bootstrap can replace existing
  cross-signing and key-backup state for the account."
  ([client]
   (bootstrap-cross-signing! client {}))
  ([client opts]
   (mx/validate! ::mx/BootstrapCrossSigningOptions opts)
   (internal/suspend-task bridge/bootstrap-cross-signing client opts)))

(defn bootstrap-cross-signing-from-passphrase!
  "Bootstraps cross-signing with a secret-storage passphrase.

  Returns the same normalized Missionary task result as
  [[bootstrap-cross-signing!]], but calls Trixnity's
  `KeyService.bootstrapCrossSigningFromPassphrase(passphrase)`.
  `passphrase` configures the generated secret storage; use `::mx/password` in
  `opts` for password-based UIA completion.

  Be aware that upstream cross-signing bootstrap can replace existing
  cross-signing and key-backup state for the account."
  ([client passphrase]
   (bootstrap-cross-signing-from-passphrase! client passphrase {}))
  ([client passphrase opts]
   (mx/validate! ::mx/passphrase passphrase)
   (mx/validate! ::mx/BootstrapCrossSigningOptions opts)
   (internal/suspend-task
    bridge/bootstrap-cross-signing-from-passphrase
    client
    passphrase
    opts)))

(defn current-backup-version
  "Returns the current active room-key-backup version, or nil when unavailable."
  [client]
  (bridge/current-backup-version client))

(defn backup-version
  "Returns a Missionary flow of the active room-key-backup version."
  [client]
  (->> (internal/observe-flow client (bridge/backup-version-flow client))
       (m/relieve {})))

(defn get-trust-level
  "Returns a Missionary flow of trust information.

  With two arguments, `user-id` resolves to the trust level of that user.

  With three arguments, the meaning depends on the first id:

  - a `@user:server` value resolves device trust for `device-id`
  - a `!room:server` value resolves the trust level for the device that sent
    the timeline `event-id`"
  ([client user-id]
   (mx/validate! ::mx/user-id user-id)
   (internal/observe-flow client (bridge/user-trust-level client user-id)))
  ([client user-id-or-room-id device-id-or-event-id]
   (if (str/starts-with? user-id-or-room-id "@")
     (do
       (mx/validate! ::mx/user-id user-id-or-room-id)
       (mx/validate! ::mx/device-id device-id-or-event-id)
       (internal/observe-flow client (bridge/device-trust-level client user-id-or-room-id device-id-or-event-id)))
     (do
       (mx/validate! ::mx/room-id user-id-or-room-id)
       (mx/validate! ::mx/event-id device-id-or-event-id)
       (internal/observe-flow client (bridge/timeline-trust-level client user-id-or-room-id device-id-or-event-id))))))

(defn get-device-keys
  "Returns a Missionary flow of device keys for `user-id`."
  [client user-id]
  (mx/validate! ::mx/user-id user-id)
  (internal/observe-flow client (bridge/device-keys-flow client user-id)))

(defn get-cross-signing-keys
  "Returns a Missionary flow of cross-signing keys for `user-id`."
  [client user-id]
  (mx/validate! ::mx/user-id user-id)
  (internal/observe-flow client (bridge/cross-signing-keys-flow client user-id)))
