= ol.trixnity.user


Room user state, receipts, presence, and permission checks.

## Upstream Mapping

This namespace wraps the user-oriented room APIs exposed by Trixnity's
`RoomService`.

The public wrappers here cover:

- room member lookup by id or as keyed flow maps
- per-user receipt and power-level observation
- permission checks for invites, bans, kicks, redactions, power changes, and
  sending events
- user presence and global account-data queries

Use xref:api/ol-trixnity-room.adoc[`ol.trixnity.room`] for room lifecycle and timeline access, and
xref:api/ol-trixnity-client.adoc[`ol.trixnity.client`] for client-wide state.

[#load-members]
== load-members




[source,clojure]
----
(load-members client room-id)
(load-members client room-id opts)
----

Loads room members for `room-id` and returns a Missionary task.

Supported opts:

| key | description
|-----|-------------
| `::mx/wait` | When true, wait for the member load to finish before resolving the task (default `true`) |

[.api-source]
link:https://github.com/outskirtslabs/trixnity-clj/blob/main/src/clj/ol/trixnity/user.clj#L26-L42[source,window=_blank]

'''

[#get-all]
== get-all




[source,clojure]
----
(get-all client room-id)
----

Returns a Missionary flow of room members keyed by user id.

[.api-source]
link:https://github.com/outskirtslabs/trixnity-clj/blob/main/src/clj/ol/trixnity/user.clj#L44-L48[source,window=_blank]

'''

[#get-by-id]
== get-by-id




[source,clojure]
----
(get-by-id client room-id user-id)
----

Returns a Missionary flow of the room member for `user-id`, or nil when unavailable.

[.api-source]
link:https://github.com/outskirtslabs/trixnity-clj/blob/main/src/clj/ol/trixnity/user.clj#L50-L55[source,window=_blank]

'''

[#get-all-receipts]
== get-all-receipts




[source,clojure]
----
(get-all-receipts client room-id)
----

Returns a Missionary flow of per-user receipt flows keyed by user id.

[.api-source]
link:https://github.com/outskirtslabs/trixnity-clj/blob/main/src/clj/ol/trixnity/user.clj#L57-L61[source,window=_blank]

'''

[#get-receipts-by-id]
== get-receipts-by-id




[source,clojure]
----
(get-receipts-by-id client room-id user-id)
----

Returns a Missionary flow of receipts for `user-id` in `room-id`.

[.api-source]
link:https://github.com/outskirtslabs/trixnity-clj/blob/main/src/clj/ol/trixnity/user.clj#L63-L68[source,window=_blank]

'''

[#get-power-level]
== get-power-level




[source,clojure]
----
(get-power-level client room-id user-id)
----

Returns a Missionary flow of the current power-level view for `user-id`.

[.api-source]
link:https://github.com/outskirtslabs/trixnity-clj/blob/main/src/clj/ol/trixnity/user.clj#L70-L75[source,window=_blank]

'''

[#can-kick-user]
== can-kick-user




[source,clojure]
----
(can-kick-user client room-id user-id)
----

Returns a Missionary flow that reports whether the current client can kick `user-id`.

[.api-source]
link:https://github.com/outskirtslabs/trixnity-clj/blob/main/src/clj/ol/trixnity/user.clj#L77-L82[source,window=_blank]

'''

[#can-ban-user]
== can-ban-user




[source,clojure]
----
(can-ban-user client room-id user-id)
----

Returns a Missionary flow that reports whether the current client can ban `user-id`.

[.api-source]
link:https://github.com/outskirtslabs/trixnity-clj/blob/main/src/clj/ol/trixnity/user.clj#L84-L89[source,window=_blank]

'''

[#can-unban-user]
== can-unban-user




[source,clojure]
----
(can-unban-user client room-id user-id)
----

Returns a Missionary flow that reports whether the current client can unban `user-id`.

[.api-source]
link:https://github.com/outskirtslabs/trixnity-clj/blob/main/src/clj/ol/trixnity/user.clj#L91-L96[source,window=_blank]

'''

[#can-invite-user]
== can-invite-user




[source,clojure]
----
(can-invite-user client room-id user-id)
----

Returns a Missionary flow that reports whether the current client can invite `user-id`.

[.api-source]
link:https://github.com/outskirtslabs/trixnity-clj/blob/main/src/clj/ol/trixnity/user.clj#L98-L103[source,window=_blank]

'''

[#can-invite]
== can-invite




[source,clojure]
----
(can-invite client room-id)
----

Returns a Missionary flow that reports whether the current client can invite users to `room-id`.

[.api-source]
link:https://github.com/outskirtslabs/trixnity-clj/blob/main/src/clj/ol/trixnity/user.clj#L105-L109[source,window=_blank]

'''

[#can-redact-event]
== can-redact-event




[source,clojure]
----
(can-redact-event client room-id event-id)
----

Returns a Missionary flow that reports whether the current client can redact `event-id`.

[.api-source]
link:https://github.com/outskirtslabs/trixnity-clj/blob/main/src/clj/ol/trixnity/user.clj#L111-L116[source,window=_blank]

'''

[#can-set-power-level-to-max]
== can-set-power-level-to-max




[source,clojure]
----
(can-set-power-level-to-max client room-id user-id)
----

Returns a Missionary flow of the maximum power level the current client may assign to `user-id`.

[.api-source]
link:https://github.com/outskirtslabs/trixnity-clj/blob/main/src/clj/ol/trixnity/user.clj#L118-L123[source,window=_blank]

'''

[#can-send-event]
== can-send-event




[source,clojure]
----
(can-send-event client room-id event-class-or-content)
----

Returns a Missionary flow that reports whether the current client can send an event.

`event-class-or-content` may be either a room-event-content class or a
concrete room-event-content instance.

[.api-source]
link:https://github.com/outskirtslabs/trixnity-clj/blob/main/src/clj/ol/trixnity/user.clj#L125-L142[source,window=_blank]

'''

[#get-presence]
== get-presence




[source,clojure]
----
(get-presence client user-id)
----

Returns a Missionary flow of presence data for `user-id`.

[.api-source]
link:https://github.com/outskirtslabs/trixnity-clj/blob/main/src/clj/ol/trixnity/user.clj#L144-L148[source,window=_blank]

'''

[#get-account-data]
== get-account-data




[source,clojure]
----
(get-account-data client event-content-class)
(get-account-data client event-content-class key)
----

Returns a Missionary flow of global account-data content.

When `key` is omitted, the empty-string state key is used.

[.api-source]
link:https://github.com/outskirtslabs/trixnity-clj/blob/main/src/clj/ol/trixnity/user.clj#L150-L161[source,window=_blank]

'''

[#get-direct-chats]
== get-direct-chats




[source,clojure]
----
(get-direct-chats client)
----

Returns a Missionary flow of the current `m.direct` mapping.

The emitted value is a map of Matrix user ids to sets of direct-room ids.

[.api-source]
link:https://github.com/outskirtslabs/trixnity-clj/blob/main/src/clj/ol/trixnity/user.clj#L163-L168[source,window=_blank]

'''

[#set-direct-chats]
== set-direct-chats




[source,clojure]
----
(set-direct-chats client mappings)
----

Writes the `m.direct` mapping and returns a Missionary task.

`mappings` must be a map of Matrix user ids to sets of room ids.

[.api-source]
link:https://github.com/outskirtslabs/trixnity-clj/blob/main/src/clj/ol/trixnity/user.clj#L170-L178[source,window=_blank]
